comments:
  blockComment: ['{', '}']

brackets:
  - [(, )]

autoClosingPairs:
  - ['{', '}']
  - [(, )]

surroundingPairs:
  - ['{', '}']
  - [(, )]
  - [comenzar, fin]

folding:
  markers:
    start: \bcomenzar\b
    end: \bfin\b
