name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Build grammars
        run: pnpm build:grammars

      - name: Publish to VSCode Marketplace
        run: pnpm dlx @vscode/vsce publish --no-dependencies -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.AZURE_PAN_TOKEN }}

      - name: Publish to Open VSX
        run: pnpm dlx ovsx publish --no-dependencies -p $OVSX_TOKEN
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
